version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./server/scenarios.txt:/app/scenarios.txt
    environment:
      - NODE_ENV=production
      - PORT=3001

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://localhost:3001

networks:
  default:
    driver: bridge